name: Create EC2 Spot Instance
on:
  workflow_dispatch:
    inputs:
      class:
        description: "Instance Family Type e.g t2.micro"
        required: true
        default: t2.micro
      chat_id:
        required: true
        description: "Chat ID Telegram"
      instance_name:
        required: true
        description: "Tag for new instance"
permissions:
  contents: write
jobs: 
  Create_Spot_Instance:
    environment: Telegram-Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Clone necessary file
        working-directory: ./create_ec2_spot
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-1"
        run: |
          aws s3 cp s3://telegram-aws-bot-s3/spot/ . --recursive
          terraform init
          echo "${{ inputs.instance_name }},${{ inputs.class }}" >> spot.txt
      - name: Apply Terraform to List Instances
        id: terraform_apply
        working-directory: ./create_ec2_spot
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-1"
        run: | 
          terraform apply -auto-approve
          echo "public_ips=$(terraform output -raw instance_public_ips)" >> $GITHUB_ENV
      - name: Save Changes
        working-directory: ./create_ec2_spot
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-1"
        run: |
          aws s3 cp spot.txt s3://telegram-aws-bot-s3/spot/spot.txt
          aws s3 cp terraform.tfstate s3://telegram-aws-bot-s3/spot/terraform.tfstate
      - name: Send Instance Info
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "chat_id":"${{inputs.chat_id}}",
            "text":"${{env.public_ips}}",
            "parse_mode":"Markdown"
            }' \
          "https://api.telegram.org/bot${{secrets.TELEGRAM_TOKEN}}/sendMessage"

