name: Create EC2 Instance
on:
  workflow_dispatch:
    inputs:
      class:
        description: "Instance Family Type e.g t2.micro"
        required: true
        default: t2.micro
      chat_id:
        required: true
        description: "Chat ID Telegram"
jobs: 
  Create_Instance:
    environment: Telegram-Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Initialize Terraform
        working-directory: ./create_ec2_on_demand
        run: terraform init
      - name: Apply Terraform to List Instances
        working-directory: ./create_ec2_on_demand
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-1"
        run: |
          terraform apply \
          -var="instance_class=${{inputs.class}}" -auto-approve
        - name: Get Outputs
          id: get_outputs
          run: |
            echo "Public IP: $(terraform output -raw instance_public_ip)"
            echo "Instance Name: $(terraform output -raw instance_name)"