name: Server Listing
on: 
  workflow_dispatch:
    inputs:
      chat_id:
        required: true
        description: Chat ID Telegram
jobs:
  Provision_EC2:
    environment: Telegram-Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Initialize Terraform
        working-directory: ./list_ec2_resources
        run: terraform init
      - name: Apply Terraform to List Instances
        working-directory: ./list_ec2_resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-1"
        run: |
          terraform apply -auto-approve
          INSTANCE_IDS=$(terraform output -json instance_ids | jq -r '.[]')
          echo "Instance IDs: $INSTANCE_IDS"
          echo "instance_ids=$INSTANCE_IDS" >> $GITHUB_ENV
      - name: Send Instance IDs Info
        run: |
          if [ -z "${{ env.instance_ids }}" ]; then
            curl -X POST -H "Content-Type: application/json" -d '{"chat_id":"${{inputs.chat_id}}","text":"No EC2 Instance found", "parse_mode":"Markdown"}' "https://api.telegram.org/bot${{secrets.TELEGRAM_TOKEN}}/sendMessage"
          else
            curl -X POST -H "Content-Type: application/json" -d '{"chat_id":"${{inputs.chat_id}}","text":"${{ env.instance_ids }}", "parse_mode":"Markdown"}' "https://api.telegram.org/bot${{secrets.TELEGRAM_TOKEN}}/sendMessage"
          fi