name: Server Auto Provisioner
on: workflow_dispatch
inputs:
  class:
    description: 'EC2 Instance Class'
    required: true
  type:
    description: 'EC2 Instance Type'
    required: true
jobs:
  Provision_EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Is Connected
        run: |
          echo "EC2 Class is ${{ inputs.class }}"
          echo "EC2 Type is ${{ inputs.type }}"