name: Server Auto Provisioner
on: 
  workflow_dispatch:
    inputs:
      class:
        description: 'EC2 Instance Class'
        required: true
      type:
        description: 'EC2 Instance Type'
        required: true
jobs:
  Provision_EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Setup Environment
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: echo "Setup Environment Done"
      - name: Initialize Terraform
        run: |
          cd list_ec2_resources
          terraform init
      - name: Apply Terraform to List Instances
        run: |
          cd list_ec2_resources
          terraform apply -auto-approve
          terraform output instance_ids
      - name: Is Connected
        run: |
          echo "EC2 Class is ${{ inputs.class }}"
          echo "EC2 Type is ${{ inputs.type }}"